// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijfyxxrmmeogkkaswumr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqZnl4eHJtbWVvZ2trYXN3dW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzQ4NDQsImV4cCI6MjA2MTU1MDg0NH0.n08eyzQKMZPY-zDjiTLmq-FWTMF8Xfmb9y5TyEonTqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);